# Vitenskapsfilosofi

## Oppgave 1

Et vitenskapelig argument er en strukturert og rasjonell presentasjon av informasjon og bevis som brukes i vitenskapelig forskning og diskusjon for å støtte eller avvise en påstand, hypotese eller teori. Vitenskapelige argumenter er grunnleggende for vitenskapelig metode og den kritiske vurderingen av vitenskapelige påstander. I denne oppgaven defineres et argument som premissene, altså de påstandene som antas å være sanne, for eksempel den empiriske dataen i et vitenskapelig argument, pluss konklusjonen, altså påstandene som er ment å bli støttet av premissene, for eksempel den vitenskapelige teorien som dataen er ment å bekrefte. Vi skiller mellom deduktive og induktive argumenter. I deduktive argumenter er konklusjonen uungåelig dersom premissene er sanne, og argumentet anses å være deduktivt gyldig dersom det opfyller dette kravet. Et eksempel på et deduktivt argument kan være: Premiss 1: Alle mennesker er dødelige. Premiss 2: Sokrates er et menneske. Konklusjon: Derfor er sokrates dødelig.

Et induktivt argument er et argument der konklusjonen er sannsynlig dersom premissene er sanne, men konklusjonen er ikke garantert sann. Induktive argumenter involverer generelt en overgang fra spesifikke observasjoner til en generell konklusjon, og denne konklusjonen er vanligvis ikke garantert å være sann, men heller sannsynlig basert på bevisene. Et eksempel på et induktivt argument kan være: Premiss 1: De siste ti dagene jeg har stått opp om morgen, har solen også stått opp. Premiss 2: De siste ti dagene vennene mine har stått opp om morgen, har solen også stått opp. Premiss 3: De siste ti dagene jeg har pratet med folk fra et annet sted i verden, har de rapportert at solen har stått opp. Konklusjon: Solen vil stå opp i morgen.

På 1700-tallet presenterte David Hume det som gjerne kalles for induksjonsproblemet. Induksjonsproblemet er et sentralt spørsmål innen vitenskapsfilosofi, og refererer til problemet med å rettferdiggjøre troen på at fremtidige hendelser vil følge de samme mønsterene som tidligere observasjoner. Et eksempel på induksjonsproblemet er hvis vi observerer at solen alltid har steget opp i fortiden, og derfor induktivt konkluderer med at den vil fortsette å stå opp i fremtiden. Et slikt argument er hverken deduktivt gyldig eller induktivt sterkt. Hvis du legger til et skjult premiss -- en antagelse om at fremtiden vil ligne på fortiden, så blir konklusjonen mere sannsynlig. Påstanden om at fremtiden vil ligne på fortiden kalles noen ganger for uniformitetsprinsippet.

Hume hevdet at det ikke er mulig å deduktivt begunne en induktiv konklusjon fordi alle induktive argumenter forutsetter uniformitetsprinsippet. Han hevdet at det ikke finnes noen logisk begrunnelse for å forvente at fremtidige hendelser ville følge de samme mønstrene som tidligere hendelser. Hume argumenterte for at våre induktive slutninger er basert på vaner eller en psykologisk forventning, og ikke på en solid logisk begrunnelse. I følge Hume kan vi altså ikke være helt sikre på, eller utlede at solen kommer til å stå opp i morgen. Vi kan ikke utlede at solen kommer til å stå opp i morgen, men vi kan heller ikke utlede at solen ikke kommer til å stå opp i morgen. På en måte kan man argumentere for at uniformitetsprinsippet er «uskyldig til det motsatte er bevist».

Humes konklusjon om at det ikke finnes noe rasjonell begrunnelse for bruken av induksjon er vanskelig, kanskje til og med umulig å unngå. Hume hevdet at alle induktive argumenter forutsetter bruk av uniformitetsprinsippet. Dette er en utfordring fordi vi ikke kan bevise at uniformitetsprinsippet er sant ved bruk av logikk. Det er enkelt å forestille seg at fremtiden vil se forskjellig ut fra fortiden. En kan heller ikke empirisk sjekke om uniformitetsprinsippet er sant ved å se på verden akuratt nå. Uniformitetsprinsippet har altså ingen rasjonell begrunnelse og derfor har heller ikke induktive argumenter noen rasjonell begrunnelse.

Selv om vi ikke har noen rasjonell begrunnelse for uniformitetsprinsippet betyr ikke det at det er irrasjonelt å bruke induksjon. Noen induktive argumenter lar vi oss overbevise av i større grad en andre. Mange relevante og pålitelige bevis, kausalitet, sansynlighet, og manglende moteksempler er med på å påvirke hvor overbevist vi blir av et induktivt argument. Til eksempel lar vi oss kanskje overbevise av påstanden om at sola vil stå opp i morgen, fordi den har stått opp så mange ganger i fortiden, og fremtiden vil ligne på fortiden på tross av at det ikke har noen rasjonell begrunnelse. Det er dessuten veldig praktisk for oss å anta at fremtiden vil ligne på fortiden i en slik sammenheng. Det fjerner bekymringer knyttet til morgendagens eksistens og gjør det mulig å legge planer for fremtiden.

## Oppgave 2

Popper mente at Humes induksjonsproblem ikke kunne løses, og at induktiv logikk er et misslykket prosjekt [@godfrey-smith2003]. Det å lete etter bekreftelse på hypoteser er i følge Popper pseudovitenskap. Det er viktig å kunne skille mellom pseudovitenskap og ekte vitenskap. Dette kalles for avgrensningsproblemet. Poppers løsning på avgrensningsproblemet var falsifisering. Popper mente at påstand S er en vitenskapelig påstand hvis, og bare hvis S er falsifiserbar [@popper2010]. For at påstand S skal være falsifiserbar må man kunne utlede en prediksjon fra S som det er mulig å empirisk sjekke.

Popper var skreptisk til Marx' historieteori, Freud's psyko-analyse og Alfred Adler's såkalte «individuell psykologi» ettersom disse teoriene lot seg forklare av alle mulige observasjoner. Til eksempel ville en Marxist ikke kunne åpne avisa uten å finne bekreftene bevis for sin tolkning av historien på hver eneste side; ikke bare i nyhetene, men også i presentasjonen -- som avslørte avisens klasseskjevhet -- og selvsagt hva avisa ikke sa [@popper1969]. Popper var derimot stor tilhenger av Einsteins relativitetsteori. Einsteins generelle relativitetsteori var svært falsifiserbar. Einstein gjorde risikable, uventede og presise prediksjoner som viste seg å være riktig. Selv om relativitetsteorien er testet empirisk og verifisert betyr ikke dette at teorien er bekreftet. I følge Popper er nemlig vitenskaplig bekreftelse av teorier umulig.

Popper foreslår en vitenskapelig syklus hvor man starter med en falsifiserbar hypotese, utleder presise prediksjoner som kan sjekkes empirisk, for så å falsifisere, lage ny hypotese, ny prediksjon, ny falsifisering osv.

Et eksempel på et vitenskapelig spørsmål kan for eksempel være: Påvirker inntak av energidrikke tannhelsen? Her kan man bruke falsifisering til å undersøke spørsmålet. Som forsker kan man formulere en hypotese som sier at «konsum av energidrikke påvirker tannhelsen negativt». Deretter gjennomfører man et ekspiriment der det samles inn empirisk data fra en gruppe mennesker og observerer inntakk av energidrikke og tannhelse. Hvis resultatene ikke viser en signifikant dårligere tannhelse hos personer som drikker mye energidrikke enn hos personer som ikke drikker energidrikke vil hypotesen bli falsifisert. I så tilfelle må forskerene lage ny hypotese, ny prediksjon og ny falsifisering. Hvis resultatene derimot viser at personer som drikker mye energidrikke får dårligere tannhelse har vi empirisk bevis for at hypotesen er sann.

En stor utfordring med falsifikasjon er at det kan føre til at en forkaster vitenskapelige teorier fordi teorien er for spesifikk og enkelt falsifiserbar. Et eksempel kan være «alle sauer er hvite». Denne påstanden kan bli falsifisert av én enkelt observasjon av for eksempel en svart sau. Selv om teorien er flasifisert er den ikke unyttig. Teorien kan være nyttig i enkelte sammenhenger, for eksempel i et bestemt fjellområde. På samme måte kan «energidrikke påvirker tannhelse negativt» bli falsifisert, men det behøver ikke å bety at teorien er unyttig.
