# Studiedesign

Hovedformålet med denne oppgaven er å undersøke hvilke studiedesign og statistiske analyser som brukes til å måle effekten olympisk vektløfting har på hurtighet i ulike studier. Oppgaven har også som mål å undersøke hvilken faktisk effekt olympisk vektløfting har på hurtighet sammenliknet med andre treningsintervensjoner. Avslutningsvis vil det bli gitt noen anbefalinger knyttet til valg av studiedesign og statistiske analyser, samt hvilken praktisk betydning funnene har og hvordan de kan anvendes.

De fem studiene som er inkludert i denne oppgaven så på effekten olympisk vektløfting har på idrettsprestasjon. Idrettsprestasjon er svært komplekst og det kreves gjerne en sammensetning av mange ferdigheter for å prestere i en idrett. Hvilke ferdigheter som er viktig er også forskjellig fra idrett til idrett. I studiene som er inkludert i denne oppgaven undersøkte de derfor ikke bare fremgang i korte sprinter, men også vertikale hopp, knebøy 1RM og løp med retningsforandring. Av de fem studiene som er med i oppgaven så sammenliknet tre av studiene effekten av olympisk vektløfting med plyometrisk trening [@chaouachi2014; @teo2016; @tricoli2005], mens de to andre sammenliknet olympisk vektløfting med tradisjonell styrkeløft inspirert trening [@helland2017; @hoffman2004].

[@chaouachi2014] sin hypotese var at olypisk vektløfting skulle gi større økning i hurtig kraftutvikling mens tradisjonell styrke ville gi større økning i ren styrke. [@teo2016] sin hypotese var at vektløfting ville gi størst fremgang i kraftutvikling sammenlignet med plyometrisk trening. [@tricoli2005] hypotetiserte at olympisk vektløfting ville gi lik fremgang på hopp, hurtighets- og agility tester som plyometrisk trening. [@hoffman2004] antok at trening med høy kraftutvikling og høy hastighet, slik som olympisk vektløfting, ville gi en større effekt på hurtighet enn trening med høy kraft og lav hastighet, slik som tradisjonell styrkeløft inspirert styrketrening.

Av de fem studiene som er inkludert i oppgaven antok tre av studiene at olympisk vektløfting skulle gi en større økning i hurtighet enn den alternative treningsintervensjonen, mens to av studiene så for seg en lik fremgang. Denne antagelsen kan skyldes flere faktorer. Mange av øvelsene i olympisk vektløfting har bevegelsesmønstere som er svært overførbare til en rekke idretter kanskje særlig pågrunn av kravene som stilles til styrke, kraft og hurtighet. I olympisk vektløfting er alltid intensjonen å flytte stanga så hurtig som mulig, så farta er allid maksimal og det stilles store krav til konsentrasjon. Derfor påvirker olympisk vektløfting nevromuskulær koordinasjon og kontroll, hurtighet på kraftutvikling og evne til å takle tunge og hurtige ekstentriske belastninger [@garhammer1992; @hydock2001]. Dette er faktorer som er viktige blandt annet for hurtighet.

Designet som blir brukt i de fem studiene som er inkludert i denne oppgaven er randomisert blindet studie. Deltakerne ble tilfeldig tildelt enten vektløftingsgruppe eller en alternativ treningsintervensjon, for eksempel tradisjonell styrkeløft inspirert styrketrening. To av studiene inkluderte også en kontrollgruppe med deltakere som ikke fulgte noe spesifikt treningsprogram [@chaouachi2014; @tricoli2005]. En fordel med en slik randomisering er at det reduserer risikoen for at systematiske skjevheter eller forstyrrende faktorer påvirker resultatene [@hulley2013]. Et eksempel på blinding kan være i studien til [@teo2016] hvor deltakerenes unike ID ble sendt til en uavhengig forsker som tilfeldig tildelte deltakerne enten olympisk vektløfting gruppen eller plyometrisk trening (representert som 1 og 2). Ved å bruke randomisert blindet studie sikrer man sammenliknbarhet mellom intervensjonsgruppene [@hulley2013]. Det ble brukt pre og post test til å måle effekt og forskjeller mellom gruppene. Studiene hadde forskjellig varighet, hvor et av studiene hadde varighet på 6 uker [@teo2016], mens tre av studiene hadde varighet på 8 uker [@helland2017; @chaouachi2014; @tricoli2005], og et studie varte i 15 uker [@hoffman2004].

Det er noe variasjon i utvalget mellom de forskjellige studiene som kan gjøre det vanskelig å sammenlikne resultatene. Tre av studiene så på atleter tidlig i 20-årene [@helland2017; @hoffman2004; @tricoli2005], mens et av studiene så på gutter mellom ti og tolv år [@chaouachi2014] og et av studiene undersøkte middels trente menn i midten av 20-årene [@teo2016]. Utvalget i studiene varierte i størrelse og de ulike studiene hadde hhv 39 [@helland2017], 63 [@chaouachi2014], 26 [@teo2016], 32 [@tricoli2005] og 20 [@hoffman2004] deltakere. [@hulley2013b] forklarer at det studier med for lite utvalg kan føre til at man går glipp av viktige effekter og føre til villedende konklusjoner. Et tilstrekkelig utvalg er viktig for å sikre statistisk styrke. En måte å regne ut den statistiske styrken på er ved å gjøre en power-test. En power-test viser oss hvor mange deltakere vi trenger for å være sikker på å oppdage en effekt hvis det faktisk er en effekt. [@hoffman2004] forklarer i sin studie at «basert på tidligere studier som har undersøkt endringer i styrke utenfor sesong, vil en utvalgsstørrelse på 20 deltakere gi minst 80% statistisk styrke på signifikansnivå p \> 0.05».

Alle studiene rapporterte resultatene som gjennomsnitt pluss minus standardavvik. [@helland2017; @chaouachi2014; @teo2016] brukte Cohens effect size til å forklare effektstørrelser. Cohens d brukes til å beskrive forskjellen mellom gruppene. Den regnes ut ved å ta forskjellen mellom gjennomsnittet for gruppene (for eksempel eksperiment gruppen og kontrollgruppen) og dele det på standardavviket på hele datamengden. En høyere Cohens d viser til en større effekt. En vanlig inndeling er: ubetydelig effekt \<0,2, liten effekt 0,2-0,6, moderat effekt 0,6-1,2, stor effekt 1,2-2, og svært stor effekt \>2,0. Cohens D gir en standardisert måling av effektstørrelsen noe som gjør det enklere å sammenlikne effektene på tvers av studier.

Gruppen som trente olympisk vektløfting hadde en forbedring på sprint-tester i alle studiene. Det var ingen forskjell i økning på sprint-tester mellom olympisk vektløfting og plyometrisk trening [@chaouachi2014; @teo2016; @tricoli2005]. Det var heller ingen forskjell mellom olympisk vektløfting og tradisjonell styrkeløft inspirert styrketrening [@helland2017; @hoffman2004]. I studiet til [@hoffman2004] gjennomførte deltakerne som hørte til tradisjonell styrkeløft inspirert styrketrening et sprint og agility program ved siden av styrketreningen. Det kan spekuleres i om dette påvirket resultatet i det studiet. Med bakgrunn i resultatene kan det se ut som at plyometrisk trening og olympisk vektløfting gir samme fremgang når det kommer til utvikling av hurtighet.

Fremtidig forskning på effekten av olympisk vektløfting på hurtighet bør gjøres som randomiserte forsøk. Ettersom flere av øvelsene i olympisk vektløfting er svært tekniske kan det være aktuelt med en tilæringsfase og en lengre intervensjonsperiode så man sikrer seg mot at resultatene ikke påvirkes av at dårlig teknikk og at man får de adaptasjonene en faktisk ønsker. Det kan også være lurt å ikke inkludere spesifikk sprint trening under intervensjonen. Dersom en skal sammenlikne olympisk vektløfting med for eksempel tradisjonell styrketrening er det svært viktig at en krontrollerer det totale treningsvolumet.

Dersom en kun er ute etter å forbedre hurtighet kan det se ut som at olympisk vektløfting, plyometrisk trening og tradisjonell styrketrening gir de samme resultatene og at du derfor kan velge den treningsformen som du trives best med. Det ser allikevel ut som at olympisk vektløfting har noen fordeler særlig når det kommer til hurtighet på kraftutvikling og løp med retningsforandringer som kan være til fordel i mange idretter.
